import "./globals.css"
import Announcement from "./components/Announcement"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Announcement />
        {children}
      </body>
    </html>
  )
}
